import { useCallback } from 'react';
import { pageview } from 'react-ga';

export type AnalyticsEventForDrawingActivity =
  | 'start-drawing-activity'
  | 'draw-letter---'
  | 'draw-letter-.-'
  | 'draw-letter-...-'
  | 'draw-letter-***-'
  | 'draw-letter-a-'
  | 'draw-letter-å-'
  | 'draw-letter-ā-'
  | 'draw-letter-ā̊-'
  | 'draw-letter-ą-'
  | 'draw-letter-b-'
  | 'draw-letter-c-'
  | 'draw-letter-d-'
  | 'draw-letter-e-'
  | 'draw-letter-ē-'
  | 'draw-letter-ǝ̄-'
  | 'draw-letter-ə-'
  | 'draw-letter-f-'
  | 'draw-letter-g-'
  | 'draw-letter-h-'
  | 'draw-letter-i-'
  | 'draw-letter-ī-'
  | 'draw-letter-j-'
  | 'draw-letter-k-'
  | 'draw-letter-l-'
  | 'draw-letter-m-'
  | 'draw-letter-n-'
  | 'draw-letter-ṇ-'
  | 'draw-letter-ŋ-'
  | 'draw-letter-ŋ<raised>v-'
  | 'draw-letter-ŋ́-'
  | 'draw-letter-o-'
  | 'draw-letter-ō-'
  | 'draw-letter-p-'
  | 'draw-letter-q-'
  | 'draw-letter-r-'
  | 'draw-letter-s-'
  | 'draw-letter-ś-'
  | 'draw-letter-š-'
  | 'draw-letter-ṣ-'
  | 'draw-letter-ṣ̌-'
  | 'draw-letter-t-'
  | 'draw-letter-u-'
  | 'draw-letter-ū-'
  | 'draw-letter-v-'
  | 'draw-letter-w-'
  | 'draw-letter-x-'
  | 'draw-letter-x́-'
  | 'draw-letter-x<raised>v-'
  | 'draw-letter-y-'
  | 'draw-letter-z-'
  | 'draw-letter-θ-';

export type AnalyticsEventForAlphabetExplorerActivity =
  | 'start-explore-alphabet-activity'
  | 'display-picker-letter-modal-in-alphabet-explorer'
  | 'explore-letter---'
  | 'explore-letter-.-'
  | 'explore-letter-...-'
  | 'explore-letter-***-'
  | 'explore-letter-a-'
  | 'explore-letter-å-'
  | 'explore-letter-ā-'
  | 'explore-letter-ā̊-'
  | 'explore-letter-ą-'
  | 'explore-letter-b-'
  | 'explore-letter-c-'
  | 'explore-letter-d-'
  | 'explore-letter-e-'
  | 'explore-letter-ē-'
  | 'explore-letter-ǝ̄-'
  | 'explore-letter-ə-'
  | 'explore-letter-f-'
  | 'explore-letter-g-'
  | 'explore-letter-h-'
  | 'explore-letter-i-'
  | 'explore-letter-ī-'
  | 'explore-letter-j-'
  | 'explore-letter-k-'
  | 'explore-letter-l-'
  | 'explore-letter-m-'
  | 'explore-letter-n-'
  | 'explore-letter-ṇ-'
  | 'explore-letter-ŋ-'
  | 'explore-letter-ŋ<raised>v-'
  | 'explore-letter-ŋ́-'
  | 'explore-letter-o-'
  | 'explore-letter-ō-'
  | 'explore-letter-p-'
  | 'explore-letter-q-'
  | 'explore-letter-r-'
  | 'explore-letter-s-'
  | 'explore-letter-ś-'
  | 'explore-letter-š-'
  | 'explore-letter-ṣ-'
  | 'explore-letter-ṣ̌-'
  | 'explore-letter-t-'
  | 'explore-letter-u-'
  | 'explore-letter-ū-'
  | 'explore-letter-v-'
  | 'explore-letter-w-'
  | 'explore-letter-x-'
  | 'explore-letter-x́-'
  | 'explore-letter-x<raised>v-'
  | 'explore-letter-y-'
  | 'explore-letter-z-'
  | 'explore-letter-θ-';
export type AnalyticsFor101NamesActivity = 'start-101-names-activity';

export type AnalyticsEvent =
  | 'load-app'
  | 'start-video-avestan-script-and-sounds'
  | 'start-transpose-activity'
  | 'transpose-activity-completed'
  | 'start-avesta-song-activity'
  | AnalyticsEventForAlphabetExplorerActivity
  | AnalyticsEventForDrawingActivity
  | AnalyticsFor101NamesActivity;
export const useAnalytics = () => {
  const addEvent = useCallback((event: AnalyticsEvent) => {
    try {
      const sanitizedEvent = event.replace(/[<>]/g, '-');
      pageview(sanitizedEvent);
    } catch (error) {
      // no op
    }
  }, []);
  return [addEvent];
};
